name: Docker build and deploy to Kubernetes

on: workflow_dispatch

jobs:

  dockerCI:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v3
      
      - name: Buildx set-up
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.REG_USERNAME }}
          password: ${{ secrets.REG_PASSWORD }}

      - name: Build and push Docker image
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          context: ./
          platforms: linux/amd64,linux/arm64/v8
          file: ./Dockerfile
          push: true
          tags: '${{ vars.DOCKER_IMAGE }}:${{ vars.APP_VERSION }}'
          labels: ${{ steps.meta.output.labels }}
          build-args: |
            APP_VERSION=${{ vars.APP_VERSION }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  kubernetesCI:

    runs-on: ubuntu-latest
    needs: dockerCI

    steps:
      - name: Checkout code (config repo)
        uses: actions/checkout@v4
        with:
          repository: pawelp29/cloud_z2_config
          ref: main
          token: ${{ secrets.CONFIG_REPO_TOKEN }}
      
      - name: Configure Git
        run: |
          git config user.name '${{ vars.GIT_USERNAME }}'
          git config user.email '${{ vars.GIT_EMAIL }}'
      
      - name: Update image tag
        run: |
          sed -i 's|image: ${{ vars.DOCKER_IMAGE }}:.*|image: ${{ vars.DOCKER_IMAGE }}:${{ vars.APP_VERSION }}|g' ./deployment.yaml

      - name: Commit and push to repo
        run: |
          git diff --quiet && git diff --staged --quiet || git commit -am 'update image version to ${{ vars.APP_VERSION }}'
          git push origin main
